lib/metaitems_web/router.ex
defmodule MetaitemsWeb.Router do
  use MetaitemsWeb, :router

  import MetaitemsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MetaitemsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MetaitemsWeb do
    pipe_through :browser

    # get "/", PageController, :index
    live "/", ItemLive.Index, :index
    live "/:username", UserLive.Profile, :index
    live "/i/coming_soon", PageLive.ComingSoon, :index
    # get "/i/coming_soon", PageController, :soon
  end

  # Other scopes may use custom stacks.
  # scope "/api", MetaitemsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MetaitemsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", MetaitemsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    # live "/users/register", UserLive.RegistrationComponent, :create
    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create


    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MetaitemsWeb do
    pipe_through [:browser, :require_authenticated_user]

    # get "/users/settings", UserSettingsController, :edit
    # put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/accounts/edit", UserLive.Settings
    live "/accounts/password/change", UserLive.PassSettings
    live "/:username/following", UserLive.Profile, :following
    live "/:username/followers", UserLive.Profile, :followers

    live "/i/new", ItemLive.New, :new

    # Admin Only for now
    live "/accounts/wallet/edit", WalletLive.WalletSettings
    live "/accounts/notsosecureplace/import_nfts", AdminLive.PolicyImport
  end

  scope "/", MetaitemsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update

    # Getting some crazy bug
    live "/i/:id", ItemLive.Show
  end
end

lib/metaitems_web/controllers/user_session_controller.ex
defmodule MetaitemsWeb.UserSessionController do
  use MetaitemsWeb, :controller

  alias Metaitems.Context.Accounts
  alias MetaitemsWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/metaitems_web/views/user_session_view.ex
defmodule MetaitemsWeb.UserSessionView do
  use MetaitemsWeb, :view
end

lib/metaitems_web/templates/user_session/new.html.heex
<div class="hero min-h-screen bg-gradient-primary">
  <div class="text-white flex-col justify-center hero-content lg:flex-row">
     <div class="text-center lg:text-left">
      <h1 class="mb-5 text-5xl font-bold">
           Please Login
          </h1> 
      <p class="mb-5">
            Thank you for your support.
      </p>
    </div> 
    
    <div class="text-black card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
      <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
      <%= if @error_message do %>
        <div class="alert alert-danger">
          <p><%= @error_message %></p>
        </div>
      <% end %>
      
      
      <div class="card-body">
        <div class="form-control">
          <label class="label">
            <%= label f, :email, class: "label-text" %>
          </label> 
          <%= email_input f, :email, required: true, placeholder: "email", class: "input input-bordered" %>
        </div> 
        <div class="form-control">
          <label class="label">
            <%= label f, :password, class: "label-text" %>
          </label> 
           <%= password_input f, :password, required: true, placeholder: "password", class: "input input-bordered" %>
          
          <%= label f, :remember_me, "Keep me logged in for 60 days" %>
          <%= checkbox f, :remember_me %>
          <label class="label">
            <a href="#" class="label-text-alt">Forgot password?</a>
          </label>
        </div> 
        <div class="form-control mt-6">
          <%= submit "Log in", class: "btn btn-primary" %>
          
        </div>
      </div>
      </.form>
        <p class="justify-center hero-content py-4">
           <a href="/">Register</a> 
          <%#= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
        </p>
    </div>
  </div>
</div>